### ISSUE TITLE
Move to Directory.Build.props

### ISSUE THREAD

**Issue by SebastianKuesters** [wemogy/generator#160]
https://github.com/wemogy/generator/blob/b828b7b8fec34d5d368ed8577e916bb39a25851f/src/sdk-dotnet/templates/%24%7Bname%7D/%24%7Bname%7D.csproj#L26

**Comment by robinmanuelthiel** [comment]
I need to check, if we really want that for EVERY project within a Solution. If yes - then this is a good idea!

**Comment by robinmanuelthiel** [comment]
Done.
