### ISSUE TITLE
Generate Commands and Queries

### ISSUE THREAD

**Issue by robinmanuelthiel** [wemogy/generator#174]
To avoid my namespace issues ;)

**Comment by robinmanuelthiel** [comment]
Form the `... .Core` folder (generated the `/Command` folder, if not already there. 

1. Ask for return value
2. Should ask me, if I want to also generate a Validator, Pre-Processor, Authorziation and Post proccessor (multi-select)

**Comment by SebastianKuesters** [comment]
[Done](https://docs-internal.wemogy.com/generator/libraries/cqrs/commands)
